[project]
name = "pot-trust-layer"
authors = []
telemetry = false
cache_dir = "./.clarinet"

[contracts.reputation]
path = "contracts/reputation.clar"
clarity_version = 2
epoch = 2.5

[contracts.vault]
path = "contracts/vault.clar"
clarity_version = 2
epoch = 2.5

[contracts.trust-core]
path = "contracts/trust-core.clar"
clarity_version = 2
epoch = 2.5

[repl.settings]
analysis = ["check_checker", "costs_v3"]

[[devnet.accounts]]
label = "deployer"
mnemonic = "fetch outside black test wash cover just actual execute nice door want airport betray quantum stamp cherry mad spread fashion brass exotic giggle"
balance = 100_000_000_000

[[devnet.accounts]]
label = "wallet_1"
mnemonic = "spoil sock coyote include verify comic jacket gain beauty tank flush victory illness edge reveal"
balance = 100_000_000_000

[[devnet.accounts]]
label = "wallet_2"
mnemonic = "arrange scale orient half ugly kid bike twin magnet joke hurt fiber ethics super receive"
balance = 100_000_000_000
